version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    ports:
      - "81:80"
    links:
      - php
    networks:
      - laravel

  php:
    build: ./src
    restart: always
    working_dir: /usr/share/nginx/html
    expose:
      - "9000"
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - laravel

  composer:
    image: composer
    volumes:
      - ./src:/app
    command: composer install

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - laravel
  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel